# Generated by Django 3.2.9 on 2022-01-18 03:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('screenshot', cloudinary.models.CloudinaryField(default='Image', max_length=255, verbose_name='image')),
                ('topics', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(max_length=300, null=True)),
                ('live_link', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
